import os

# Define paths relative to the test/verification directory (where this script lives)
# But wait, the bash script runs from test/verification (cd "$(dirname "$0")")
# So paths are relative to test/verification
WORK_DIR = "riscof_work"
HTML_FILE = "report.html"
CSS_FILE = "style.css"

html_path = os.path.join(WORK_DIR, HTML_FILE)
css_path = os.path.join(WORK_DIR, CSS_FILE)

def inline_css():
    if not os.path.exists(html_path):
        print(f"Error: {html_path} not found.")
        return
    if not os.path.exists(css_path):
        print(f"Error: {css_path} not found.")
        return

    print(f"Inlining CSS from {css_path} into {html_path}...")

    with open(css_path, 'r') as f:
        css_content = f.read()

    with open(html_path, 'r') as f:
        html_content = f.read()

    # The specific tag generated by RISCOF
    link_tag = '<link href="style.css" rel="stylesheet" type="text/css"/>'
    
    if link_tag in html_content:
        new_style_block = f'<style>\n{css_content}\n</style>'
        new_html_content = html_content.replace(link_tag, new_style_block)
        
        with open(html_path, 'w') as f:
            f.write(new_html_content)
        print("Success: CSS inlined.")
    else:
        print("Warning: CSS link tag not found in HTML. Already inlined?")

if __name__ == "__main__":
    inline_css()
